name: Docker Image CI
on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Docker Build
        run: |
          echo " pwd "
          pwd
          
          echo " ls "
          ls 
          echo " pwd "
          cd Test
          echo " cd Tes "
          ls
          docker build -t github_provar . 
      - name: list folders
        run: |
          echo " pwd "
          pwd
          echo " ls -Rd $PWD/* "
          ls -Rd $PWD/*
          echo " cd .. "
          cd ..
          echo " ls -ld -- */ "
          ls -ld -- */
          echo " ls -Rd $PWD/*"
          ls -Rd $PWD/*
          echo " cd ANT folder "
          cd /home/runner/work/Provar/Provar/Provar_ANT_latest
          ls -Rd $PWD/*
          
          
    # -
    #  name: Docker run
    #    run: |
    #     docker run -t --name github_provar github_provar
