name: Docker Image CI
on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Docker Build
        run: |
          echo " pwd "
          pwd
          
          ## echo " ls "
          ## ls 
          ## echo " pwd "
          ## cd Test
          ## echo " cd Tes "
          ## ls
          
          mkdir ProvarHome
          curl -O https://download.provartesting.com/latest/Provar_ANT_latest.zip
          
          unzip -o Provar_ANT_latest.zip -d ProvarHome
         
          export PROVAR_HOME="ProvarHome"
          
          ## echo $PROVAR_HOME  
          echo "ls $PROVAR_HOME  "
          ls $PROVAR_HOME  
          
          ## echo " ls -Rd $PWD/* ProvarHome  "
          ## ls -Rd $PWD/* ProvarHome  
          
          ## echo " ls -ld -- */  /srv/Provar/Provar_ANT_latest"
          ## ls -ld -- */   /srv/Provar/Provar_ANT_latest
          
          ## echo " ls -ld -- */ /home/runner/work/Provar/Provar/ProvarHome "
          ## ls -ld -- */ /home/runner/work/Provar/Provar/ProvarHome
          
          ## echo "ls -l /home/runner/work/Provar/Provar/ProvarHome/"
          ## ls -l /home/runner/work/Provar/Provar/ProvarHome/
          
          ## ls -ld -- */ /home/runner/work/Provar/Provar/ProvarHome/ProvarHome
          
          
          ## echo "ls -ld -- */ ProvarHome"
          ##ls -ld -- */ ProvarHome
          
          cd Test
          docker build -t github_provar . 
          
      - name: list folders
        run: |
          echo " pwd "
          pwd
          ## echo " ls -Rd $PWD/* "
          ## ls -Rd $PWD/*
          ## echo " cd .. "
          ## cd ..
          ## echo " ls -ld -- */ "
          ## ls -ld -- */
          ## echo " ls -Rd $PWD/*"
          ## ls -Rd $PWD/*
          ## echo " cd ANT folder "
          ## cd /home/runner/work/Provar/
          #ls -Rd $PWD/*
          
          
      -
        name: Docker run
        run: |
         docker run -t --name github_provar github_provar
